4.3 Prep
Tzahi12345/YoutubeDL-Material pull request #657
Opened 2022-06-20 20:15 UTC by Tzahi12345

Summary:
* Updated UI for creating/modifying playlists (see demo below)
* Playlists are now file type agnostic (that is, you can now mix and match audio files and video files into a playlist)
* Subscription file cards now use the new ones on the home page
* Version updated to v4.3
* Updated translations
* Updated API/models
* Various code cleanup
* Fixed issue where playlist order could not be rearranged

**Demo**:
https://user-images.githubusercontent.com/707413/174672249-00990e94-2886-4748-b49a-e2f3761d80c1.mp4

### This will be a WIP. Once this is merged, v4.3 will be released!

2022-06-20 22:49 UTC, GlassedSilver commented
Maybe removing the recommendations to use the nightly branch would be a good idea.

Same for docker-compose.yml.

2022-06-21 05:46 UTC, Tzahi12345 commented on backend/twitch.js
> +    const result = await exec(`tcd --video ${vodId} --client-id ${clientID} --client-secret ${clientSecret} --format json -o appdata`, {stdio:[0,1,2]});
Not sure how to address this... We can ignore it or figure out our own way to sanitize.

2022-06-24 03:43 UTC, martadinata666 commented
Add to wiki solution for RPI4 or other devices that mongodb throw exception.
https://github.com/Tzahi12345/YoutubeDL-Material/issues/614#issuecomment-1142216713

and add some references
* https://jira.mongodb.org/browse/DOCS-14684
* https://github.com/docker-library/mongo/issues/485
* https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610
* https://www.mongodb.com/community/forums/t/core-dump-on-mongodb-5-0-on-rpi-4/115291

2022-06-24 03:54 UTC, Tzahi12345 commented
> Add to wiki solution for RPI4 or other devices that mongodb throw exception (132).

I'm honestly down to just target mongo:4.4.6

Not sure if there's a reason to be at v5 anyways... @GlassedSilver thoughts?

2022-06-24 04:00 UTC, martadinata666 commented
> > Add to wiki solution for RPI4 or other devices that mongodb throw exception (132).
> 
> I'm honestly down to just target mongo:4.4.6
> 
> Not sure if there's a reason to be at v5 anyways... @GlassedSilver thoughts?

Yeah, updating compose to target `mongo:4.4` also will do, it just we also need to add reason `why` because as you know some folks just `why not :latest?`

2022-06-24 04:04 UTC, Tzahi12345 commented
> Yeah, updating compose to target `mongo:4.4` also will do, it just we also need to add reason `why` because as you know some folks just `why not :latest?`

I did just try on a test instance downgrading and it was not pretty. I'll probably go with your first suggestion and add something to the README for rpi 4

2022-06-26 05:04 UTC, GlassedSilver requested changes
small change I would like to ask for from what I was able to spot so far, other than that LGTM :)

2022-06-27 00:09 UTC, GlassedSilver commented on src/app/components/unified-file-card/unified-file-card.component.html
> +                <mat-icon>delete_forever</mat-icon><ng-container i18n="Delete forever subscription video button">Delete and don't download again</ng-container>
The original wording you used in this PR seemed a bit technical. A better UX wording would be to refer to this as "Delete and don't download again" like we discussed on Discord, so I felt free to commit this change myself. :) Same as below

2022-06-27 00:09 UTC, GlassedSilver commented on src/app/components/unified-file-card/unified-file-card.component.html
> +            <button *ngIf="!file_obj.sub_id && use_youtubedl_archive" (click)="emitDeleteFile(true)" mat-menu-item><mat-icon>delete_forever</mat-icon><ng-container i18n="Delete and don't download aga
Refer to my comment for above (line 37)

2022-06-27 00:13 UTC, GlassedSilver approved these changes
LGTM :)

2022-06-27 01:02 UTC, GlassedSilver approved these changes

2022-06-27 01:13 UTC, merged